name: waveglide
description: Waveglide

version: 0.0.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  flutter_blue: ^0.7.1+1
  # when updating, create new podfile
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.6+3
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

#call "flutter packages pub run flutter_launcher_icons:main" to recompile icons


flutter:
  uses-material-design: true
  assets:
    - assets/images/
